projects:
  Agrim8-API:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: ap-southeast-2
        apiId: xlfux3hy5fgwpgxp7wfjqckvgy
        maxDepth: 2
extensions:
  amplify:
    version: 3
